//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arista
    {
        public int Id { get; set; }
        public int IdDestinoInicial { get; set; }
        public int IdDestinoFinal { get; set; }
        public decimal Distancia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Destino DestinoInicial { get; set; }
        public virtual Destino DestinoFinal { get; set; }
    }
}
