//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destino
    {
        public Destino()
        {
            this.AristasIniciales = new HashSet<Arista>();
            this.AristasFinales = new HashSet<Arista>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
        public decimal Coordenada_X { get; set; }
        public decimal Coordenada_Y { get; set; }
        public int Tipo { get; set; }
        public int IdUsuarioAgrega { get; set; }
    
        public virtual ICollection<Arista> AristasIniciales { get; set; }
        public virtual ICollection<Arista> AristasFinales { get; set; }
        public virtual Usuario UsuarioAgrega { get; set; }
    }
}
